name: Deploy to Neocities
description: Deploys a folder to Neocities using its Ruby CLI
author: Jonathan Chang
inputs: 
  key:
    description: Neocities API token
    required: true
  dir:
    description: Local directory to deploy
    required: true
  clean:
    description: Also delete remote files that don't exist locally
    default: false
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.key }}
    - ${{ inputs.dir }}
    - ${{ inputs.clean }}
